create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  fecha_creacion timestamptz not null default now(),
  fecha_evento date not null default current_date,
  hora_evento time without time zone not null default localtime(0),
  estado text not null default 'pendiente'
);

alter table public.eventos
  add column if not exists fecha_creacion timestamptz not null default now();

alter table public.eventos
  add column if not exists fecha_evento date not null default current_date;

alter table public.eventos
  add column if not exists hora_evento time without time zone not null default localtime(0);

alter table public.eventos
  add column if not exists estado text not null default 'pendiente';

update public.eventos
set fecha_evento = fecha_creacion::date
where fecha_evento is null;

update public.eventos
set hora_evento = fecha_creacion::time
where hora_evento is null;

update public.eventos
set estado = 'pendiente'
where estado is null
  or estado not in ('pendiente', 'realizado');

alter table public.eventos
  alter column titulo set not null,
  alter column fecha_creacion set default now(),
  alter column fecha_creacion set not null,
  alter column fecha_evento set default current_date,
  alter column fecha_evento set not null,
  alter column hora_evento set default localtime(0),
  alter column hora_evento set not null,
  alter column estado set default 'pendiente',
  alter column estado set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'eventos_estado_check'
      and conrelid = 'public.eventos'::regclass
  ) then
    alter table public.eventos
      add constraint eventos_estado_check
      check (estado in ('pendiente', 'realizado'));
  end if;
end $$;
